@HOST = http://localhost:5000

# test@example.com hash: DJkchqZcmGSQkYJ7cdFnc6mayeKILjel71xWHJyX+eiXHuCH2CZXjpKRCw9zUPUczQkrCx4htcwrBZpqaaYbqw eaeQQX0An%2FxQ%2FjAg9fa2M0CpiGS6Z6FcuPXO9l%2BUQ7E%3D
# Registration token 1: TYCN_N8MEYT886ZMPnPrGmcl1iVjxyS1exr_fANxwSaK8PQ4JacyzY9s1SdRN-XdS-7m3o8B9wW6P8XSpWNjJw
# 'salt' email hash: SOmhjd4uG1jmh1ewfIq7CVSRpt3eIQd39Gw69uxKlIRdfXFdT68PDiWD+0+/HmRHnQW7ciDDjvaZ8jOunMr4wg

### Register account
POST {{HOST}}/register
Content-Type: text/plain

test@example.com
Passw0rd

### Confirm account
GET {{HOST}}/register/DJkchqZcmGSQkYJ7cdFnc6mayeKILjel71xWHJyX+eiXHuCH2CZXjpKRCw9zUPUczQkrCx4htcwrBZpqaaYbqw/TYCN_N8MEYT886ZMPnPrGmcl1iVjxyS1exr_fANxwSaK8PQ4JacyzY9s1SdRN-XdS-7m3o8B9wW6P8XSpWNjJw #?returnUrl=https://google.com

### Change password
POST {{HOST}}/password
Authorization: SHA3 salt SOmhjd4uG1jmh1ewfIq7CVSRpt3eIQd39Gw69uxKlIRdfXFdT68PDiWD+0+/HmRHnQW7ciDDjvaZ8jOunMr4wg Passw0rd
Content-Type: text/plain

Passw0rd

### Set new value
PUT {{HOST}}/dashboard/0
Authorization: SHA3 salt SOmhjd4uG1jmh1ewfIq7CVSRpt3eIQd39Gw69uxKlIRdfXFdT68PDiWD+0+/HmRHnQW7ciDDjvaZ8jOunMr4wg Passw0rd
Content-Type: text/plain

value2

### Get value
GET {{HOST}}/dashboard
Authorization: SHA3 salt SOmhjd4uG1jmh1ewfIq7CVSRpt3eIQd39Gw69uxKlIRdfXFdT68PDiWD+0+/HmRHnQW7ciDDjvaZ8jOunMr4wg Passw0rd

### Get value (no auth)
GET {{HOST}}/dashboard

### Update value
PUT {{HOST}}/dashboard/1
Authorization: SHA3 salt SOmhjd4uG1jmh1ewfIq7CVSRpt3eIQd39Gw69uxKlIRdfXFdT68PDiWD+0+/HmRHnQW7ciDDjvaZ8jOunMr4wg Passw0rd
Content-Type: text/plain

value4
