@HOST = http://localhost:5000

# test@example.com hash: eaeQQX0An/xQ/jAg9fa2M0CpiGS6Z6FcuPXO9l+UQ7E= eaeQQX0An%2FxQ%2FjAg9fa2M0CpiGS6Z6FcuPXO9l%2BUQ7E%3D
# 'salt' email hash: qMhdMUx9WemyWUqzrgdzGZsU239cOuROhizjO+5kSpI=

### Register account
POST {{HOST}}/register
Content-Type: text/plain

test@example.com
Passw0rd

### Confirm account
GET {{HOST}}/register/eaeQQX0An%2FxQ%2FjAg9fa2M0CpiGS6Z6FcuPXO9l%2BUQ7E%3D/Ow0IOxdBFNCiFIR62Vuz48ETOsUDl5rqcj7%2FX33%2F8SI=?returnUrl=https://google.com

### Change password
POST {{HOST}}/password
Authorization: SHA256 salt qMhdMUx9WemyWUqzrgdzGZsU239cOuROhizjO+5kSpI= Passw0rd
Content-Type: text/plain

Passw0rd

### Set new value
PUT {{HOST}}/dashboard/0
Authorization: SHA256 salt qMhdMUx9WemyWUqzrgdzGZsU239cOuROhizjO+5kSpI= Passw0rd
Content-Type: text/plain

value2

### Get value
GET {{HOST}}/dashboard
Authorization: SHA256 salt qMhdMUx9WemyWUqzrgdzGZsU239cOuROhizjO+5kSpI= Passw0rd

### Get value (no auth)
GET {{HOST}}/dashboard

### Update value
PUT {{HOST}}/dashboard/3
Authorization: SHA256 salt qMhdMUx9WemyWUqzrgdzGZsU239cOuROhizjO+5kSpI= Passw0rd
Content-Type: text/plain

value4
